apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.minio.secretName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  username: {{ .Values.minio.username | b64enc | quote }}
  password: {{ .Values.minio.password | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres.secretName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  username: {{ .Values.postgres.username | b64enc | quote }}
  password: {{ .Values.postgres.password | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.redis.secretName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  password: {{ .Values.redis.password | b64enc | quote }}