apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-serving
  namespace: clinical-mlops
  labels:
    app: model-serving
    tier: ml-pipeline
    layer: level4
spec:
  replicas: 3
  selector:
    matchLabels:
      app: model-serving
  template:
    metadata:
      labels:
        app: model-serving
        tier: ml-pipeline
        layer: level4
    spec:
      containers:
      - name: model-serving
        image: ghcr.io/clinical-trials-service/clinical-mlops/model-serving:v1.0.0
        ports:
        - containerPort: 8000
        env:
        - name: MLFLOW_TRACKING_URI
          value: "http://mlflow:5000"
        - name: S3_ENDPOINT
          value: "http://minio:9000"
        - name: S3_BUCKET_MODELS
          value: "clinical-models"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: accessKey
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: secretKey
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: model-serving
  namespace: clinical-mlops
  labels:
    app: model-serving
    tier: ml-pipeline
    layer: level4
spec:
  selector:
    app: model-serving
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  type: ClusterIP