ssl: false

server:
  port: 4900
  host: "0.0.0.0"

log:
  level: info
  format: json

# Pipeline configuration directory
pipeline-configuration-file: "/usr/share/data-prepper/pipelines/pipelines.yaml"

# Data Prepper buffer settings
buffer:
  type: bounded_blocking
  buffer_max_size: 256000000  # 256MB
  buffer_max_time: 10000    # 10 seconds

# Metrics and monitoring
metrics:
  enabled: true
  host: "0.0.0.0"
  port: 4901

# Processors settings
processor:
  # Maximum number of concurrent operations
  max_concurrency: 4
  
  # Memory settings
  heap_size: 512m
  
  # Circuit breaker settings
  circuit_breaker:
    enabled: true
    failure_threshold: 50
    timeout: 30000

# Security settings (disabled for development)
ssl_provider: None
auth:
  plugin_class: None