temporal_windows:
  short: 3600
  medium: 21600
  long: 86400

feature_version: "1.0.0"

label:
  prediction_window_hours: 24
  positive_class_name: "adverse_event"

feature_groups:
  
  temporal_vitals:
    enabled: true
    metrics:
      - heart_rate
      - blood_pressure_systolic
      - blood_pressure_diastolic
      - temperature
      - spo2
    aggregations:
      - mean
      - std
      - min
      - max
      - trend
    windows:
      - short
      - medium
      - long
  
  temporal_derived:
    enabled: true
    metrics:
      - pulse_pressure
      - mean_arterial_pressure
    aggregations:
      - mean
      - std
      - trend
    windows:
      - short
      - medium
      - long
  
  lab_results:
    enabled: true
    tests:
      - wbc
      - hemoglobin
      - platelet
      - creatinine
      - alt
      - ast
    time_windows:
      - 24
      - 72
    aggregations:
      - latest
      - mean
      - trend
      - change_from_baseline
    
  medications:
    enabled: true
    high_risk_drugs:
      - warfarin
      - insulin
      - opioids
      - chemotherapy
    features:
      - current_medications
      - high_risk_medication_flag
      - polypharmacy_count
      - days_on_medication
  
  patient_context:
    enabled: true
    features:
      - trial_site
      - trial_arm
      - days_since_enrollment
      - time_of_day
      - day_of_week
  
  derived_features:
    enabled: true
    interactions:
      - name: "vital_instability_score"
        formula: "col('heart_rate_std_24h') + col('bp_systolic_std_24h') + col('temperature_std_24h')"
      - name: "hemodynamic_stress"
        formula: "col('heart_rate_mean_1h') * col('bp_systolic_mean_6h') / 10000"
      - name: "fever_tachycardia_interaction"
        formula: "col('heart_rate_mean_1h') * col('temperature_mean_1h')"

output:
  offline_store:
    path: "s3a://clinical-mlops/features/offline/"
    format: "parquet"
    partition_by: "date"
    compression: "snappy"
  
  online_store:
    host: "redis"
    port: 6379
    key_pattern: "patient:{patient_id}:features"
    ttl_hours: 72

quality_checks:
  enabled: true
  null_threshold: 0.5
  variance_threshold: 0.01
  
spark:
  shuffle_partitions: 200
  cache_intermediate: true
  repartition_count: 10