spring:
  application:
    name: clinical-data-gateway

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:development}

# IBM MQ Configuration
ibm:
  mq:
    queueManager: ${IBM_MQ_QUEUE_MANAGER:CLINICAL_QM}
    channel: ${IBM_MQ_CHANNEL:DEV.APP.SVRCONN}
    connName: ${IBM_MQ_CONNNAME:clinical-mq(1414)}
    user: ${IBM_MQ_USER:app}
    password: ${IBM_MQ_PASSWORD:clinical123}
    userAuthenticationMQCSP: ${IBM_MQ_USERAUTHENTICATIONMQCSP:true}

server:
  port: ${SERVER_PORT:8080}
  address: 0.0.0.0
  servlet:
    context-path: /
  error:
    include-stacktrace: never
    include-message: always
  compression:
    enabled: true
    mime-types: application/json,text/plain

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true
