apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: default
  namespace: clinical-mlops
spec:
  metrics:
  - providers:
    - name: prometheus
  - overrides:
    - match:
        metric: ALL_METRICS
      tagOverrides:
        destination_service:
          operation: UPSERT
          value: "destination.service.name"
        source_service:
          operation: UPSERT
          value: "source.service.name"
  accessLogging:
  - providers:
    - name: otel
    - name: envoy
  tracing:
  - providers:
    - name: otel