# MLflow
mlflow:
  enabled: true
  replicaCount: 1
  image:
    repository: mlflow
    pullPolicy: IfNotPresent
    tag: "latest"
  service:
    type: ClusterIP
    port: 5000
    targetPort: 5000
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1
      memory: 2Gi

# Model Training
modelTraining:
  enabled: true
  replicaCount: 1
  image:
    repository: model-training
    pullPolicy: IfNotPresent
    tag: "latest"
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 2
      memory: 4Gi

# Model Serving
modelServing:
  enabled: true
  replicaCount: 2
  image:
    repository: model-serving
    pullPolicy: IfNotPresent
    tag: "latest"
  service:
    type: ClusterIP
    port: 8080
    targetPort: 8080
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 1
      memory: 512Mi
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80

# Service Monitor
serviceMonitor:
  enabled: true
  interval: 30s
  path: /metrics