apiVersion: v1
kind: Secret
metadata:
  name: airflow-secrets
  namespace: clinical-mlops
  labels:
    app: airflow
    tier: orchestration
    layer: level5
type: Opaque
data:
  # Generate with: python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
  fernet-key: cTg3MjV0M3N0MW5nczNjdXJpdHk6Z2VuZXJhdGVkLWZlcm5ldC1rZXk=
  # Generate with: python -c "import secrets; print(secrets.token_hex(32))"
  secret-key: NjQ2NTczNzQ2NTczNzQ2NTczNzQ2NTczNzQ2NTczNzQ2NTczNzQ2NTczNzQ2NTczNzQ2NTczNzQ2NTczNzQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: clinical-mlops
  labels:
    app: minio
    tier: infrastructure
    layer: level0
type: Opaque
data:
  accessKey: bWluaW9hZG1pbg==  # minioadmin
  secretKey: bWluaW9hZG1pbg==  # minioadmin