apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-airflow
  namespace: clinical-mlops
  labels:
    app: postgres-airflow
    tier: orchestration
    layer: level5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-airflow
  template:
    metadata:
      labels:
        app: postgres-airflow
        tier: orchestration
        layer: level5
    spec:
      containers:
      - name: postgres-airflow
        image: postgres:15-alpine
        env:
        - name: POSTGRES_USER
          value: "airflow"
        - name: POSTGRES_PASSWORD
          value: "airflow"
        - name: POSTGRES_DB
          value: "airflow"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-airflow-data
          mountPath: /var/lib/postgresql/data
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - airflow
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - airflow
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: postgres-airflow-data
        persistentVolumeClaim:
          claimName: postgres-airflow-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-airflow
  namespace: clinical-mlops
  labels:
    app: postgres-airflow
    tier: orchestration
    layer: level5
spec:
  selector:
    app: postgres-airflow
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-airflow-pvc
  namespace: clinical-mlops
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi