apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-service
  namespace: clinical-mlops
  labels:
    app: monitoring-service
    tier: observability
    layer: level6
spec:
  replicas: 2
  selector:
    matchLabels:
      app: monitoring-service
  template:
    metadata:
      labels:
        app: monitoring-service
        tier: observability
        layer: level6
    spec:
      containers:
      - name: monitoring-service
        image: monitoring-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: PROMETHEUS_URL
          value: "http://prometheus:9090"
        - name: GRAFANA_URL
          value: "http://grafana:3000"
        - name: OPENSEARCH_URL
          value: "http://opensearch:9200"
        - name: ALERT_THRESHOLD_DRIFT
          value: "0.1"
        - name: ALERT_THRESHOLD_PERFORMANCE
          value: "0.95"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: monitoring-service
  namespace: clinical-mlops
  labels:
    app: monitoring-service
    tier: observability
    layer: level6
spec:
  selector:
    app: monitoring-service
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP