apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: clinical-gateway-bluegreen
  namespace: clinical-mlops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: clinical-gateway
      app.kubernetes.io/name: clinical-gateway
      app.kubernetes.io/component: api
  strategy:
    blueGreen:
      activeService: clinical-gateway-active
      previewService: clinical-gateway-preview
      autoPromotionEnabled: false
      scaleDownDelaySeconds: 30
      prePromotionAnalysis:
        templates:
        - templateName: success-rate
        args:
        - name: service-name
          value: clinical-gateway-preview
      postPromotionAnalysis:
        templates:
        - templateName: success-rate
        args:
        - name: service-name
          value: clinical-gateway-active
  template:
    metadata:
      labels:
        app: clinical-gateway
        app.kubernetes.io/name: clinical-gateway
        app.kubernetes.io/component: api
        app.kubernetes.io/part-of: clinical-mlops
    spec:
      containers:
      - name: clinical-gateway
        image: clinical-gateway:latest
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: clinical-gateway-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: clinical-gateway-secrets
              key: redis-url
        - name: KAFKA_BROKERS
          value: "kafka:9092"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: clinical-gateway-active
  namespace: clinical-mlops
  labels:
    app: clinical-gateway
    app.kubernetes.io/name: clinical-gateway
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: clinical-mlops
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: clinical-gateway
    app.kubernetes.io/name: clinical-gateway
---
apiVersion: v1
kind: Service
metadata:
  name: clinical-gateway-preview
  namespace: clinical-mlops
  labels:
    app: clinical-gateway
    app.kubernetes.io/name: clinical-gateway
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: clinical-mlops
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: clinical-gateway
    app.kubernetes.io/name: clinical-gateway