apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: model-serving-bluegreen
  namespace: clinical-mlops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: model-serving
      app.kubernetes.io/name: model-serving
      app.kubernetes.io/component: ml
  strategy:
    blueGreen:
      activeService: model-serving-active
      previewService: model-serving-preview
      autoPromotionEnabled: false
      scaleDownDelaySeconds: 60
      prePromotionAnalysis:
        templates:
        - templateName: latency-check
        args:
        - name: service-name
          value: model-serving-preview
        - name: latency-threshold
          value: "100ms"
      postPromotionAnalysis:
        templates:
        - templateName: latency-check
        args:
        - name: service-name
          value: model-serving-active
        - name: latency-threshold
          value: "100ms"
  template:
    metadata:
      labels:
        app: model-serving
        app.kubernetes.io/name: model-serving
        app.kubernetes.io/component: ml
        app.kubernetes.io/part-of: clinical-mlops
    spec:
      containers:
      - name: model-serving
        image: model-serving:latest
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: MODEL_PATH
          valueFrom:
            configMapKeyRef:
              name: model-serving-config
              key: model-path
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: model-serving-secrets
              key: redis-url
        - name: LOG_LEVEL
          value: "INFO"
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 1
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: model-serving-active
  namespace: clinical-mlops
  labels:
    app: model-serving
    app.kubernetes.io/name: model-serving
    app.kubernetes.io/component: ml
    app.kubernetes.io/part-of: clinical-mlops
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: model-serving
    app.kubernetes.io/name: model-serving
---
apiVersion: v1
kind: Service
metadata:
  name: model-serving-preview
  namespace: clinical-mlops
  labels:
    app: model-serving
    app.kubernetes.io/name: model-serving
    app.kubernetes.io/component: ml
    app.kubernetes.io/part-of: clinical-mlops
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: model-serving
    app.kubernetes.io/name: model-serving