apiVersion: apps/v1
kind: Deployment
metadata:
  name: clinical-data-gateway
  namespace: clinical-mlops
  labels:
    app: clinical-data-gateway
    tier: data-ingestion
    layer: level1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: clinical-data-gateway
  template:
    metadata:
      labels:
        app: clinical-data-gateway
        tier: data-ingestion
        layer: level1
    spec:
      containers:
      - name: clinical-data-gateway
        image: clinical-data-gateway:latest
        ports:
        - containerPort: 8080
        env:
        - name: SERVER_PORT
          value: "8080"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-broker:9092"
        - name: SPRING_PROFILES_ACTIVE
          value: "kubernetes"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: clinical-data-gateway
  namespace: clinical-mlops
  labels:
    app: clinical-data-gateway
    tier: data-ingestion
    layer: level1
spec:
  selector:
    app: clinical-data-gateway
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP