apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer
  namespace: clinical-mlops
  labels:
    app: kafka-consumer
    tier: data-ingestion
    layer: level1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
        tier: data-ingestion
        layer: level1
    spec:
      containers:
      - name: kafka-consumer
        image: kafka-consumer:latest
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-broker:9092"
        - name: KAFKA_TOPIC_CLINICAL_DATA
          value: "clinical-data"
        - name: KAFKA_TOPIC_LAB_RESULTS
          value: "lab-results"
        - name: KAFKA_TOPIC_MEDICATIONS
          value: "medications"
        - name: KAFKA_TOPIC_VITALS
          value: "vitals"
        - name: S3_ENDPOINT
          value: "http://minio:9000"
        - name: S3_BUCKET
          value: "clinical-data"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: accessKey
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: secretKey
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "ps aux | grep python | grep consumer.py"
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "netstat -tulpn | grep :9092 || exit 1"
          initialDelaySeconds: 10
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-consumer
  namespace: clinical-mlops
  labels:
    app: kafka-consumer
    tier: data-ingestion
    layer: level1
spec:
  selector:
    app: kafka-consumer
  ports:
  - port: 9092
    targetPort: 9092
    protocol: TCP
  type: ClusterIP